version: "3.8"

services:
  watchtower:
    image: watchtower-worker
    volumes:
      - ./service:/app/service
      - ./worker/config.yaml:/app/worker/config.yaml
      - ./worker/param.yaml:/app/worker/param.yaml
    environment:
      - RUST_LOG=info
    working_dir: /app
    healthcheck:
      test: ["CMD", "ps", "aux", "|", "grep", "watch_tower_worker"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: >
      sh -c "

        # BRP
        /usr/local/bin/watch_tower_worker --rule-path /app/service/brp/balance.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/brp/height.yaml &

        # CCCP
        /usr/local/bin/watch_tower_worker --rule-path /app/service/cccp/height.yaml &

        # CCCP Round Sync
        /usr/local/bin/watch_tower_worker --rule-path /app/service/cccp/roundsync/core.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/cccp/roundsync/eth.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/cccp/roundsync/eth_sepolia.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/cccp/roundsync/bnb.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/cccp/roundsync/bsc_testnet.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/cccp/roundsync/base.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/cccp/roundsync/base_sepolia.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/cccp/roundsync/arbitrum.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/cccp/roundsync/arbitrum_sepolia.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/cccp/roundsync/pol.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/cccp/roundsync/oasys.yaml &

        # CCCP Status
        /usr/local/bin/watch_tower_worker --rule-path /app/service/cccp/status/bifrost-full-node-00.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/cccp/status/bifrost-full-node-01.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/cccp/status/bifrost-full-node-02.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/cccp/status/bifrost-full-node-03.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/cccp/status/bifrost-full-node-04.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/cccp/status/bifrost-full-node-05.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/cccp/status/bifrost-full-node-06.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/cccp/status/bifrost-validator-00.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/cccp/status/bifrost-validator-01.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/cccp/status/bifrost-validator-02.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/cccp/status/Coinplug.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/cccp/status/Delight.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/cccp/status/Jerry.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/cccp/status/MCH.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/cccp/status/OKJ.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/cccp/status/Theori.yaml &

        # Node Status
        /usr/local/bin/watch_tower_worker --rule-path /app/service/node/status/bifrost-basic-node-01.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/node/status/bifrost-basic-node-02.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/node/status/bifrost-basic-node-03.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/node/status/bifrost-basic-node-04.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/node/status/bifrost-basic-node-05.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/node/status/bifrost-basic-node-06.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/node/status/bifrost-full-node-00.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/node/status/bifrost-full-node-01.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/node/status/bifrost-full-node-02.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/node/status/bifrost-full-node-03.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/node/status/bifrost-full-node-04.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/node/status/bifrost-full-node-05.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/node/status/bifrost-full-node-06.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/node/status/bifrost-validator-00.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/node/status/bifrost-validator-01.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/node/status/bifrost-validator-02.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/node/status/Coinplug.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/node/status/Delight.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/node/status/Jerry.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/node/status/KDDI.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/node/status/MCH.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/node/status/Nansen.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/node/status/OKJ.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/node/status/PacificMeta.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/node/status/Theori.yaml &

        # APY Rate Monitor
        /usr/local/bin/watch_tower_worker --rule-path /app/service/apy_monitor/rate/btcfi.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/apy_monitor/rate/bifi.yaml &

        # Oracle
        ## Balance

        ### Bifrost
        #### Chainlink
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/balance/bifrost_chainlink_eth.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/balance/bifrost_chainlink_usdc.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/balance/bifrost_chainlink_usdt.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/balance/bifrost_chainlink_bnb.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/balance/bifrost_chainlink_pol.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/balance/bifrost_chainlink_dai.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/balance/bifrost_chainlink_btc.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/balance/bifrost_chainlink_btcusd.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/balance/bifrost_chainlink_wstbfc.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/balance/bifrost_chainlink_euro.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/balance/bifrost_chainlink_lp_btcusd.yaml &

        #### Aggregator
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/balance/bifrost_aggregator.yaml &

        ### Kaia
        #### Chainlink
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/balance/kaia_chainlink_btc.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/balance/kaia_chainlink_dai.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/balance/kaia_chainlink_usdt.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/balance/kaia_chainlink_xrp.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/balance/kaia_chainlink_eth.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/balance/kaia_chainlink_usdc.yaml &

        ### Base
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/balance/base_chainlink_btc.yaml &

        ##Time
        ###Bifrost
        #### Chainlink
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/time/bifrost_chainlink_eth.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/time/bifrost_chainlink_usdc.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/time/bifrost_chainlink_usdt.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/time/bifrost_chainlink_dai.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/time/bifrost_chainlink_bnb.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/time/bifrost_chainlink_pol.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/time/bifrost_chainlink_btc.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/time/bifrost_chainlink_euro.yaml &

        #### Bifnet
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/time/bifrost_bifnet_bfc.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/time/bifrost_bifnet_bifi.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/time/bifrost_bifnet_eth.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/time/bifrost_bifnet_usdc.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/time/bifrost_bifnet_usdt.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/time/bifrost_bifnet_bnb.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/time/bifrost_bifnet_pol.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/time/bifrost_bifnet_dai.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/time/bifrost_bifnet_wbtc.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/time/bifrost_bifnet_btcb.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/time/bifrost_bifnet_btc.yaml &

        #### Aggregator
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/time/bifrost_aggregator_eth.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/time/bifrost_aggregator_usdc.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/time/bifrost_aggregator_usdt.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/time/bifrost_aggregator_bnb.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/time/bifrost_aggregator_pol.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/time/bifrost_aggregator_bfc.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/time/bifrost_aggregator_wstbfc.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/time/bifrost_aggregator_btcusd.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/time/bifrost_aggregator_bifi.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/time/bifrost_aggregator_dai.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/time/bifrost_aggregator_wbtc.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/time/bifrost_aggregator_btc.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/time/bifrost_aggregator_lp_btcusd.yaml &
        
        ###Kaia
        #### Chainlink
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/time/kaia_chainlink_btc.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/time/kaia_chainlink_dai.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/time/kaia_chainlink_usdt.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/time/kaia_chainlink_xrp.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/time/kaia_chainlink_eth.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/time/kaia_chainlink_usdc.yaml &
        
        ###Base
        #### Chainlink
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/time/base_chainlink_btc.yaml &


        # Oracle Manager Decision
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/decision/bifrost_oraclemanager_bfc.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/decision/bifrost_oraclemanager_bifi.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/decision/bifrost_oraclemanager_eth.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/decision/bifrost_oraclemanager_bnb.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/decision/bifrost_oraclemanager_pol.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/decision/bifrost_oraclemanager_usdc.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/decision/bifrost_oraclemanager_usdt.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/decision/bifrost_oraclemanager_dai.yaml &

        # Oracle Manager Insufficient
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/insufficient/bifrost_oraclemanager_bfc.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/insufficient/bifrost_oraclemanager_bifi.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/insufficient/bifrost_oraclemanager_eth.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/insufficient/bifrost_oraclemanager_bnb.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/insufficient/bifrost_oraclemanager_pol.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/insufficient/bifrost_oraclemanager_usdc.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/insufficient/bifrost_oraclemanager_usdt.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/insufficient/bifrost_oraclemanager_dai.yaml &

        # Oracle Majority
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/majority/bifrost_chainlink.yaml &

        # Oracle Price
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/price/bifrost_chainlink_bifnet_eth.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/price/bifrost_chainlink_bifnet_usdc.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/price/bifrost_chainlink_bifnet_usdt.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/price/bifrost_chainlink_bifnet_bnb.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/price/bifrost_chainlink_bifnet_pol.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/price/bifrost_chainlink_bifnet_dai.yaml &
        /usr/local/bin/watch_tower_worker --rule-path /app/service/oracle/price/bifrost_chainlink_bifnet_btc.yaml &

        # Keep container running and wait for all processes
        wait
      "
