name: Base Round Sync Check
time_interval: 600
script: |
  active_status = 2;

  bifrostBN = Bifrost.LatestBlock();
  bifrost_round_status = Bifrost.CCCP.LatestRound.Status(bifrostBN);

  baseBN = Base.LatestBlock();
  base_round_status = Base.CCCP.LatestRound.Status(baseBN);
  sync_diff = when bifrost_round_status > base_round_status then bifrost_round_status - base_round_status else base_round_status - bifrost_round_status;

  when sync_diff > active_status then Slack.Send(CCCP, '*CCCP Round Sync 알람* 🚀\n <!here>\n> Sync 차이 : ' + sync_diff + '\n> Bifrost : ' + bifrost_round_status + '\n> Base : ' + base_round_status) else false;
